# Dealing with the dataset

#### Importing the dataset

In [1]:
import pandas as pd
data = pd.read_csv(r'C:\Users\marcu\Desktop\MACHINE_LEARNING\DATABASES\BEER_RECIPES_DATASET\recipeData.csv', encoding='latin1')
data

BeerID                             Name  \
0           1                Vanilla Cream Ale   
1           2      Southern Tier Pumking clone   
2           3      Zombie Dust Clone - EXTRACT   
3           4    Zombie Dust Clone - ALL GRAIN   
4           5  Bakke Brygg Belgisk Blonde 50 l   
...       ...                              ...   
73856   73857                    Amber Alfie 2   
73857   73858                          Rye IPA   
73858   73859                        SK-Kölsch   
73859   73860                  Flata Rødkløver   
73860   73861            Elvis Juice IPA Clone   

                                                     URL  \
0           /homebrew/recipe/view/1633/vanilla-cream-ale   
1      /homebrew/recipe/view/16367/southern-tier-pumk...   
2      /homebrew/recipe/view/5920/zombie-dust-clone-e...   
3      /homebrew/recipe/view/5916/zombie-dust-clone-a...   
4      /homebrew/recipe/view/89534/bakke-brygg-belgis...   
...                                                  ...   
73856         /homebrew/recipe/view/609673/amber-alfie-2   
73857               /homebrew/recipe/view/610955/rye-ipa   
73858                      /homebrew/recipe/view/586891/   
73859                      /homebrew/recipe/view/603788/   
73860  /homebrew/recipe/view/613776/elvis-juice-ipa-c...   

                                    Style  StyleID  Size(L)     OG     FG  \
0                               Cream Ale       45    21.77  1.055  1.013   
1      Holiday/Winter Special Spiced Beer       85    20.82  1.083  1.021   
2                            American IPA        7    18.93  1.063  1.018   
3                            American IPA        7    22.71  1.061  1.017   
4                       Belgian Blond Ale       20    50.00  1.060  1.010   
...                                   ...      ...      ...    ...    ...   
73856                  British Strong Ale       36    21.00  1.052  1.012   
73857              Specialty IPA: Rye IPA      151    10.00  1.059  1.010   
73858                                 NaN      111    16.00  1.046  1.008   
73859                       Irish Red Ale       92    24.00  1.051  1.014   
73860                        American IPA        7    20.00  1.060  1.010   

        ABV    IBU  ...  BoilGravity  Efficiency  MashThickness  \
0      5.48  17.65  ...        1.038        70.0            NaN   
1      8.16  60.65  ...        1.070        70.0            NaN   
2      5.91  59.25  ...          NaN        70.0            NaN   
3      5.80  54.48  ...          NaN        70.0            NaN   
4      6.48  17.84  ...        1.050        72.0            NaN   
...     ...    ...  ...          ...         ...            ...   
73856  5.22  39.73  ...        1.060        63.0            3.0   
73857  6.37  59.21  ...        1.034        60.0            NaN   
73858  5.01  25.42  ...        1.041        65.0            NaN   
73859  4.82  25.65  ...        1.043        72.0            NaN   
73860  6.55  57.09  ...        1.056        70.0            NaN   

             SugarScale    BrewMethod  PitchRate PrimaryTemp PrimingMethod  \
0      Specific Gravity     All Grain        NaN       17.78    corn sugar   
1      Specific Gravity     All Grain        NaN         NaN           NaN   
2      Specific Gravity       extract        NaN         NaN           NaN   
3      Specific Gravity     All Grain        NaN         NaN           NaN   
4      Specific Gravity     All Grain        NaN       19.00    Sukkerlake   
...                 ...           ...        ...         ...           ...   
73856  Specific Gravity     All Grain       1.25       20.00           NaN   
73857  Specific Gravity          BIAB       0.50       22.00           NaN   
73858  Specific Gravity          BIAB       0.35       17.00       sucrose   
73859  Specific Gravity     All Grain        NaN       18.00    Sukkerlake   
73860  Specific Gravity  Partial Mash        NaN       18.00           NaN   

        PrimingAmo

#### Verifiying the dataset

In [2]:
data.isnull().sum()

BeerID               0
Name                 1
URL                  0
Style              596
StyleID              0
Size(L)              0
OG                   0
FG                   0
ABV                  0
IBU                  0
Color                0
BoilSize             0
BoilTime             0
BoilGravity       2990
Efficiency           0
MashThickness    29864
SugarScale           0
BrewMethod           0
PitchRate        39252
PrimaryTemp      22662
PrimingMethod    67095
PrimingAmount    69087
UserId           50490
dtype: int64

In [3]:
missing_percent = (data.isnull().sum()/len(data['BeerID']))*100
missing_percent

BeerID            0.000000
Name              0.001354
URL               0.000000
Style             0.806921
StyleID           0.000000
Size(L)           0.000000
OG                0.000000
FG                0.000000
ABV               0.000000
IBU               0.000000
Color             0.000000
BoilSize          0.000000
BoilTime          0.000000
BoilGravity       4.048144
Efficiency        0.000000
MashThickness    40.432705
SugarScale        0.000000
BrewMethod        0.000000
PitchRate        53.143066
PrimaryTemp      30.681957
PrimingMethod    90.839550
PrimingAmount    93.536508
UserId           68.358132
dtype: float64

In [4]:
data.dtypes

BeerID             int64
Name              object
URL               object
Style             object
StyleID            int64
Size(L)          float64
OG               float64
FG               float64
ABV              float64
IBU              float64
Color            float64
BoilSize         float64
BoilTime           int64
BoilGravity      float64
Efficiency       float64
MashThickness    float64
SugarScale        object
BrewMethod        object
PitchRate        float64
PrimaryTemp      float64
PrimingMethod     object
PrimingAmount     object
UserId           float64
dtype: object

#### Manipulating the dataset

In [5]:
data.drop(['URL','Name', 'Style','PrimingMethod','PrimingAmount', 'UserId' ], inplace =True, axis = 1)
data

BeerID  StyleID  Size(L)     OG     FG   ABV    IBU  Color  BoilSize  \
0           1       45    21.77  1.055  1.013  5.48  17.65   4.83     28.39   
1           2       85    20.82  1.083  1.021  8.16  60.65  15.64     24.61   
2           3        7    18.93  1.063  1.018  5.91  59.25   8.98     22.71   
3           4        7    22.71  1.061  1.017  5.80  54.48   8.50     26.50   
4           5       20    50.00  1.060  1.010  6.48  17.84   4.57     60.00   
...       ...      ...      ...    ...    ...   ...    ...    ...       ...   
73856   73857       36    21.00  1.052  1.012  5.22  39.73   6.96     18.00   
73857   73858      151    10.00  1.059  1.010  6.37  59.21   7.90     17.00   
73858   73859      111    16.00  1.046  1.008  5.01  25.42   3.63     18.00   
73859   73860       92    24.00  1.051  1.014  4.82  25.65  14.12     28.00   
73860   73861        7    20.00  1.060  1.010  6.55  57.09   8.65     12.00   

       BoilTime  BoilGravity  Efficiency  MashThickness        SugarScale  \
0            75        1.038        70.0            NaN  Specific Gravity   
1            60        1.070        70.0            NaN  Specific Gravity   
2            60          NaN        70.0            NaN  Specific Gravity   
3            60          NaN        70.0            NaN  Specific Gravity   
4            90        1.050        72.0            NaN  Specific Gravity   
...         ...          ...         ...            ...               ...   
73856        60        1.060        63.0            3.0  Specific Gravity   
73857        60        1.034        60.0            NaN  Specific Gravity   
73858        90        1.041        65.0            NaN  Specific Gravity   
73859        60        1.043        72.0            NaN  Specific Gravity   
73860        60        1.056        70.0            NaN  Specific Gravity   

         BrewMethod  PitchRate  PrimaryTemp  
0         All Grain        NaN        17.78  
1         All Grain        NaN          NaN  
2           extract        NaN          NaN  
3         All Grain        NaN          NaN  
4         All Grain        NaN        19.00  
...             ...        ...          ...  
73856     All Grain       1.25        20.00  
73857          BIAB       0.50        22.00  
73858          BIAB       0.35        17.00  
73859     All Grain        NaN        18.00  
73860  Partial Mash        NaN        18.00  

[73861 rows x 17 columns]

In [1]:
data['BoilGravity'].fillna(data['BoilGravity'].median(), inplace = True)
data['MashThickness'].fillna(data['MashThickness'].median(), inplace = True)
data['PitchRate'].fillna(data['PitchRate'].mean(), inplace = True)
data['PrimaryTemp'].fillna(data['PrimaryTemp'].median(), inplace = True)
data

NameError: name 'data' is not defined

In [62]:
pd.set_option("display.max_columns", 176)
pd.set_option("max_rows", 176)

In [8]:
data02 = data.loc[(data['StyleID']==7)|(data['StyleID']==10)|(data['StyleID']==134)\
                  |(data['StyleID']==9)|(data['StyleID']==4)|\
                  (data['StyleID']==30)|(data['StyleID']==86)|(data['StyleID']==12)|\
                 (data['StyleID']==92)|(data['StyleID']==6)|(data['StyleID']==175)|\
                  (data['StyleID']==39)]

In [9]:
data02

BeerID  StyleID  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  \
2           3        7    18.93  1.063  1.018  5.91   59.25   8.98     22.71   
3           4        7    22.71  1.061  1.017  5.80   54.48   8.50     26.50   
5           6       10    24.61  1.055  1.013  5.58   40.12   8.00     29.34   
6           7       86    22.71  1.072  1.018  7.09  268.71   6.33     30.28   
9          10       86    20.82  1.080  1.017  8.22   93.02   8.29     28.39   
...       ...      ...      ...    ...    ...   ...     ...    ...       ...   
73853   73854        7    18.93  1.073  1.018  7.15    0.00   6.01     22.71   
73854   73855       10    18.93  1.064  1.016  6.26    0.00   9.60     28.39   
73855   73856        7    22.71  1.065  1.014  6.71   49.35   4.73     15.14   
73859   73860       92    24.00  1.051  1.014  4.82   25.65  14.12     28.00   
73860   73861        7    20.00  1.060  1.010  6.55   57.09   8.65     12.00   

       BoilTime  BoilGravity  Efficiency  MashThickness        SugarScale  \
2            60     1.353955        70.0       2.127235  Specific Gravity   
3            60     1.353955        70.0       2.127235  Specific Gravity   
5            70     1.047000        79.0       2.127235  Specific Gravity   
6            90     1.353955        75.0       2.127235  Specific Gravity   
9            60     1.058000        70.0       2.127235  Specific Gravity   
...         ...          ...         ...            ...               ...   
73853        60     1.060000        70.0       2.127235  Specific Gravity   
73854        60     1.042000        75.0       2.127235  Specific Gravity   
73855        30     1.098000        55.0       2.127235  Specific Gravity   
73859        60     1.043000        72.0       2.127235  Specific Gravity   
73860        60     1.056000        70.0       2.127235  Specific Gravity   

         BrewMethod  PitchRate  PrimaryTemp  
2           extract   0.750468    19.175641  
3         All Grain   0.750468    19.175641  
5         All Grain   1.000000    19.175641  
6         All Grain   0.750468    19.175641  
9         All Grain   0.750468    21.110000  
...             ...        ...          ...  
73853          BIAB   0.750468    19.175641  
73854          BIAB   0.750468    19.175641  
73855  Partial Mash   0.500000    19.175641  
73859     All Grain   0.750468    18.000000  
73860  Partial Mash   0.750468    18.000000  

[35424 rows x 17 columns]

In [10]:
data['SugarScale'].value_counts()

Specific Gravity    71959
Plato                1902
Name: SugarScale, dtype: int64

In [11]:
data['BrewMethod'].value_counts()

All Grain       49692
BIAB            12016
extract          8626
Partial Mash     3527
Name: BrewMethod, dtype: int64

In [12]:
SugarScale_encode = pd.get_dummies(data02['SugarScale'])
SugarScale_encode

Plato  Specific Gravity
2          0                 1
3          0                 1
5          0                 1
6          0                 1
9          0                 1
...      ...               ...
73853      0                 1
73854      0                 1
73855      0                 1
73859      0                 1
73860      0                 1

[35424 rows x 2 columns]

In [13]:
BrewMethod_encode = pd.get_dummies(data02['BrewMethod'])
BrewMethod_encode

All Grain  BIAB  Partial Mash  extract
2              0     0             0        1
3              1     0             0        0
5              1     0             0        0
6              1     0             0        0
9              1     0             0        0
...          ...   ...           ...      ...
73853          0     1             0        0
73854          0     1             0        0
73855          0     0             1        0
73859          1     0             0        0
73860          0     0             1        0

[35424 rows x 4 columns]

In [14]:
data03 = pd.concat([data02, SugarScale_encode, BrewMethod_encode], axis = 1)
data03

BeerID  StyleID  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  \
2           3        7    18.93  1.063  1.018  5.91   59.25   8.98     22.71   
3           4        7    22.71  1.061  1.017  5.80   54.48   8.50     26.50   
5           6       10    24.61  1.055  1.013  5.58   40.12   8.00     29.34   
6           7       86    22.71  1.072  1.018  7.09  268.71   6.33     30.28   
9          10       86    20.82  1.080  1.017  8.22   93.02   8.29     28.39   
...       ...      ...      ...    ...    ...   ...     ...    ...       ...   
73853   73854        7    18.93  1.073  1.018  7.15    0.00   6.01     22.71   
73854   73855       10    18.93  1.064  1.016  6.26    0.00   9.60     28.39   
73855   73856        7    22.71  1.065  1.014  6.71   49.35   4.73     15.14   
73859   73860       92    24.00  1.051  1.014  4.82   25.65  14.12     28.00   
73860   73861        7    20.00  1.060  1.010  6.55   57.09   8.65     12.00   

       BoilTime  BoilGravity  Efficiency  MashThickness        SugarScale  \
2            60     1.353955        70.0       2.127235  Specific Gravity   
3            60     1.353955        70.0       2.127235  Specific Gravity   
5            70     1.047000        79.0       2.127235  Specific Gravity   
6            90     1.353955        75.0       2.127235  Specific Gravity   
9            60     1.058000        70.0       2.127235  Specific Gravity   
...         ...          ...         ...            ...               ...   
73853        60     1.060000        70.0       2.127235  Specific Gravity   
73854        60     1.042000        75.0       2.127235  Specific Gravity   
73855        30     1.098000        55.0       2.127235  Specific Gravity   
73859        60     1.043000        72.0       2.127235  Specific Gravity   
73860        60     1.056000        70.0       2.127235  Specific Gravity   

         BrewMethod  PitchRate  PrimaryTemp  Plato  Specific Gravity  \
2           extract   0.750468    19.175641      0                 1   
3         All Grain   0.750468    19.175641      0                 1   
5         All Grain   1.000000    19.175641      0                 1   
6         All Grain   0.750468    19.175641      0                 1   
9         All Grain   0.750468    21.110000      0                 1   
...             ...        ...          ...    ...               ...   
73853          BIAB   0.750468    19.175641      0                 1   
73854          BIAB   0.750468    19.175641      0                 1   
73855  Partial Mash   0.500000    19.175641      0                 1   
73859     All Grain   0.750468    18.000000      0                 1   
73860  Partial Mash   0.750468    18.000000      0                 1   

       All Grain  BIAB  Partial Mash  extract  
2              0     0             0        1  
3              1     0             0        0  
5              1     0             0        0  
6              1     0             0        0  
9              1     0             0        0  
...          ...   ...           ...      ...  
73853          0     1             0        0  
73854          0     1             0        0  
73855          0     0             1        0  
73859          1     0             0        0  
73860          0     0             1        0  

[35424 rows x 23 columns]

In [15]:
data04 = data03.drop(['SugarScale', 'BrewMethod'], axis =1)
data04

BeerID  StyleID  Size(L)     OG     FG   ABV     IBU  Color  BoilSize  \
2           3        7    18.93  1.063  1.018  5.91   59.25   8.98     22.71   
3           4        7    22.71  1.061  1.017  5.80   54.48   8.50     26.50   
5           6       10    24.61  1.055  1.013  5.58   40.12   8.00     29.34   
6           7       86    22.71  1.072  1.018  7.09  268.71   6.33     30.28   
9          10       86    20.82  1.080  1.017  8.22   93.02   8.29     28.39   
...       ...      ...      ...    ...    ...   ...     ...    ...       ...   
73853   73854        7    18.93  1.073  1.018  7.15    0.00   6.01     22.71   
73854   73855       10    18.93  1.064  1.016  6.26    0.00   9.60     28.39   
73855   73856        7    22.71  1.065  1.014  6.71   49.35   4.73     15.14   
73859   73860       92    24.00  1.051  1.014  4.82   25.65  14.12     28.00   
73860   73861        7    20.00  1.060  1.010  6.55   57.09   8.65     12.00   

       BoilTime  BoilGravity  Efficiency  MashThickness  PitchRate  \
2            60     1.353955        70.0       2.127235   0.750468   
3            60     1.353955        70.0       2.127235   0.750468   
5            70     1.047000        79.0       2.127235   1.000000   
6            90     1.353955        75.0       2.127235   0.750468   
9            60     1.058000        70.0       2.127235   0.750468   
...         ...          ...         ...            ...        ...   
73853        60     1.060000        70.0       2.127235   0.750468   
73854        60     1.042000        75.0       2.127235   0.750468   
73855        30     1.098000        55.0       2.127235   0.500000   
73859        60     1.043000        72.0       2.127235   0.750468   
73860        60     1.056000        70.0       2.127235   0.750468   

       PrimaryTemp  Plato  Specific Gravity  All Grain  BIAB  Partial Mash  \
2        19.175641      0                 1          0     0             0   
3        19.175641      0                 1          1     0             0   
5        19.175641      0                 1          1     0             0   
6        19.175641      0                 1          1     0             0   
9        21.110000      0                 1          1     0             0   
...            ...    ...               ...        ...   ...           ...   
73853    19.175641      0                 1          0     1             0   
73854    19.175641      0                 1          0     1             0   
73855    19.175641      0                 1          0     0             1   
73859    18.000000      0                 1          1     0             0   
73860    18.000000      0                 1          0     0             1   

       extract  
2            1  
3            0  
5            0  
6            0  
9            0  
...        ...  
73853        0  
73854        0  
73855        0  
73859        0  
73860        0  

[35424 rows x 21 columns]

In [16]:
data = data04

# Verifying the best algorithm

### Importing the  commom libraries

In [17]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

### Setting the target and predictor variables

In [18]:
y = data['StyleID']
x = data.drop('StyleID', axis = 1)

#### Seeting the train and test variables

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

## KNN Algorithm

#### Importing libraries

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

#### Normalizing the predictor variables

In [21]:
normalizer = MinMaxScaler(feature_range = (0, 1))
x_norm = normalizer.fit_transform(x)

#### Setting the parameter values will be tested

In [22]:
K_values = np.array([3,5,7,9,11])
distance_calc = ['minkowski', 'chebyshev']
#P_values = np.array([1,2,3,4])
grid_values = {'n_neighbors': K_values, 'metric': distance_calc}#, 'p': P_values}

#### Creating the model

In [23]:
model = KNeighborsClassifier()

#### Creating the grid

In [24]:
gridKNN = GridSearchCV(estimator = model, param_grid = grid_values, cv = 3, n_jobs = -1)

#### Applying the grid

In [25]:
gridKNN.fit(x_norm, y)

GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['minkowski', 'chebyshev'],
                         'n_neighbors': array([ 3,  5,  7,  9, 11])})

#### Result

In [26]:
print('Best accuracy: ', gridKNN.best_score_)
print('Best K: ', gridKNN.best_estimator_.n_neighbors)
print('Best distance: ', gridKNN.best_estimator_.metric)
print('Best p value: ', gridKNN.best_estimator_.p)

Best accuracy:  0.11845076784101173
Best K:  11
Best distance:  minkowski
Best p value:  2


## Naive Bayes

#### Importing libraries

In [31]:
from sklearn.naive_bayes import GaussianNB

#### Creating the model

In [32]:
model = GaussianNB()

#### Applying the model

In [33]:
skfold = StratifiedKFold(n_splits = 10)
result = cross_val_score(model, x, y, cv = skfold)

#### Result

In [35]:
print(f'Accuracy: {result.mean()}')

Accuracy: 0.44785832778322565


## Decision Tree

#### Importing libraries

In [47]:
from sklearn.tree import DecisionTreeClassifier

#### Setting the parameter values will be tested

In [48]:
min_splits = np.array([2,3,4,5,6,7,8])
max_level = np.array([3,4,5,6])
algorithm = ['gini', 'entropy']
grid_values = {'min_samples_split':min_splits, 'max_depth':max_level, 'criterion': algorithm}

#### Creating the model

In [49]:
model = DecisionTreeClassifier()

#### Creating the grid

In [50]:
gridDecisionTree = GridSearchCV(estimator = model, param_grid = grid_values, cv = 3, n_jobs = -1)

#### Applying the grid

In [51]:
gridDecisionTree.fit(x,y)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': array([3, 4, 5, 6]),
                         'min_samples_split': array([2, 3, 4, 5, 6, 7, 8])})

#### Result

In [52]:
print(f'Min Split: {gridDecisionTree.best_estimator_.min_samples_split}')
print(f'Max Depht: {gridDecisionTree.best_estimator_.max_depth}')
print(f'Selected Algorithm: {gridDecisionTree.best_estimator_.criterion}')
print(f'Accuracy: {gridDecisionTree.best_score_}')

Min Split: 2
Max Depht: 4
Selected Algorithm: entropy
Accuracy: 0.516796522131888


## Using the best algorithm and its best parameters

#### Defining the algorithm and parameters

In [53]:
model = DecisionTreeClassifier(min_samples_split = 2, max_depth = 4, criterion = 'entropy')

#### Aplying the model at the training data

In [54]:
model.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

#### Verifying the accuracy in the test data

In [58]:
result = model.score(x_test, y_test)
print(f'Accuracy: {result}')

Accuracy: 0.5236168611215657


#### Analysing the prediction

In [66]:
prediction = model.predict(x_test)
prediction

array([ 7, 10,  7, ..., 12, 30, 30], dtype=int64)

#### Confusion Matrix

In [64]:
from sklearn.metrics import confusion_matrix
matrix =  confusion_matrix(y_test, prediction)
print(matrix)

[[ 320   27  104    0  124    8    8    0   12    0    0    0]
 [  48  180   42    0    0   55    4    0    7    0    0    0]
 [  47   10 2868    0  336   63   95    0  191    0    0    0]
 [  38   34  157    0  160   59  244    0    8    0    0    0]
 [  63    2  760    0 1262    5  171    0    7    0    0    0]
 [   2   12    8    0    7  346    0    0    2    0    0    0]
 [   3    0   42    0  108    2  344    0    1    0    0    0]
 [  40   20   79    0   97   21   52    0    7    0    0    0]
 [  10    0  164    0   12   17    1    0  245    0    0    0]
 [ 217   43   22    0   59    8    2    0    4    0    0    0]
 [  21   14  202    0  270   11  248    0    3    0    0    0]
 [   1    5   11    0   34    2  290    0    0    0    0    0]]
